---
name: test
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install renovate-config-validator with npm
        run: npm i -g renovate
      - run: renovate --version
      - run: mv .renovaterc renovate.json
      - name: renovate.json is OK
        run: renovate-config-validator
      - run: mv renovate.json .renovaterc
      - name: renovate-config-validator doesn't work with .renovaterc 
        run: renovate-config-validator
