---
name: test
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - name: Install renovate-config-validator with npm
        run: npm i -g renovate
      - run: renovate --version
      - run: mv .renovaterc renovate.json
      - name: renovate.json is OK
        run: renovate-config-validator
      - run: mv renovate.json .renovaterc
      - name: renovate-config-validator doesn't work with .renovaterc 
        run: renovate-config-validator
